"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ArrowRight, CalendarDays, FileText, Link2, LoaderCircle, Network, RefreshCw, Search, Sparkles, Users } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { Card, EmptyState, ErrorState, LoadingState, PageHeader, StatusBadge } from "@/components/ui";
import { api, ApiError } from "@/lib/api";

const types=["ALL","PERSON","ORGANIZATION","PROJECT","TASK","DATE","TECHNOLOGY","TOPIC","LOCATION","DOCUMENT"] as const;
type EntityType=Exclude<(typeof types)[number],"ALL">;
type Node={id:string;name:string;normalized:string;type:EntityType;documentCount:number};
type Edge={id:string;sourceEntityId:string;targetEntityId:string;type:string;confidence:number;documentId?:string};
type Graph={nodes:Node[];edges:Edge[];counts:{entities:number;relationships:number;connectedDocuments:number;linkedTasks:number};topConnectedEntities:{id:string;name:string;type:EntityType;connections:number}[]};
type SearchResult={id:string;name:string;type:EntityType;documents:{id:string;name:string;status:string}[];excerpts:{documentId:string;excerpt:string}[];tasks:{id:string;title:string;status:string;priority:string}[]};
type Detail={entity:{id:string;name:string;type:EntityType};incomingRelations:{id:string;type:string;sourceEntity:{id:string;name:string;type:EntityType}}[];outgoingRelations:{id:string;type:string;targetEntity:{id:string;name:string;type:EntityType}}[];sourceDocuments:{id:string;name:string;status:string}[];sourceExcerpts:{documentId:string;excerpt:string;pageNumber?:number;chunkIndex?:number}[];connectedTasks:{id:string;title:string;status:string;priority:string;dueDate?:string}[];connectedDates:{id:string;name:string;type:EntityType}[]};
type Answer={mode:string;synthesisAvailable:boolean;status?:string;answer:string;matchedEntities:{id:string;name:string;type:EntityType}[];citations:{documentId:string;documentName:string;chunkIndex:number;pageNumber?:number;excerpt:string}[];evidence:{documentId:string;documentName:string;chunkIndex:number;pageNumber?:number;excerpt:string}[]};

export default function KnowledgePage(){
 const client=useQueryClient(),[type,setType]=useState<(typeof types)[number]>("ALL"),[search,setSearch]=useState(""),[selected,setSelected]=useState<string|null>(null),[question,setQuestion]=useState("");
 const graph=useQuery({queryKey:["knowledge-graph",type],queryFn:()=>api<Graph>(`/knowledge-graph${type==="ALL"?"":`?type=${type}`}`),retry:false});
 const results=useQuery({queryKey:["knowledge-search",search,type],queryFn:()=>api<SearchResult[]>(`/knowledge-graph/search?q=${encodeURIComponent(search.trim())}${type==="ALL"?"":`&type=${type}`}`),enabled:search.trim().length>0,retry:false});
 const detail=useQuery({queryKey:["knowledge-entity",selected],queryFn:()=>api<Detail>(`/knowledge-graph/entities/${selected}`),enabled:Boolean(selected),retry:false});
 const rebuild=useMutation({mutationFn:()=>api<{rebuiltDocuments:number}>("/knowledge-graph/rebuild",{method:"POST"}),onSuccess:async()=>{await client.invalidateQueries({queryKey:["knowledge-graph"]});await client.invalidateQueries({queryKey:["knowledge-search"]})}});
 const ask=useMutation({mutationFn:()=>api<Answer>("/knowledge-graph/questions",{method:"POST",body:JSON.stringify({question})})});
 const visible=search.trim()?results.data??[]:graph.data?.nodes??[];
 useEffect(()=>{if(!selected&&graph.data?.nodes[0])setSelected(graph.data.nodes[0].id)},[graph.data,selected]);
 const names=useMemo(()=>new Map(graph.data?.nodes.map(node=>[node.id,node.name])??[]),[graph.data]);
 function submit(event:FormEvent){event.preventDefault();if(question.trim())ask.mutate()}
 return <AppShell title="Knowledge Graph">
  <PageHeader eyebrow="WORKSPACE INTELLIGENCE" title="Workspace Knowledge Graph" description="Discover connections across documents, people, tasks and dates." actions={<button className="button button-primary" type="button" onClick={()=>rebuild.mutate()} disabled={rebuild.isPending}>{rebuild.isPending?<LoaderCircle className="spin"/>:<RefreshCw/>}{rebuild.isPending?"Building graph…":"Build workspace graph"}</button>}/>
  {rebuild.isError&&<div className="form-error" role="alert">{rebuild.error instanceof ApiError?rebuild.error.message:"The graph could not be rebuilt."}</div>}
  {graph.isLoading?<LoadingState label="Loading workspace graph"/>:graph.isError||!graph.data?<ErrorState title="Knowledge graph unavailable" description="Apply the graph migration and verify that the API is running."/>:<>
   <section className="knowledge-stats"><Stat icon={<Network/>} label="Total entities" value={graph.data.counts.entities}/><Stat icon={<Link2/>} label="Relationships" value={graph.data.counts.relationships}/><Stat icon={<FileText/>} label="Connected documents" value={graph.data.counts.connectedDocuments}/><Stat icon={<Users/>} label="Linked tasks" value={graph.data.counts.linkedTasks}/></section>
   <Card className="knowledge-toolbar"><label><Search/><span className="sr-only">Search entities</span><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Search an entity, such as Gemini" maxLength={100}/></label><select value={type} onChange={event=>{setType(event.target.value as (typeof types)[number]);setSelected(null)}} aria-label="Entity type"><option value="ALL">All entity types</option>{types.slice(1).map(value=><option key={value} value={value}>{label(value)}</option>)}</select></Card>
   <div className="knowledge-layout">
    <Card className="knowledge-network"><div className="card-header"><div><p>{search.trim()?"SEARCH RESULTS":"RELATIONSHIP VIEW"}</p><h2>{search.trim()?`${visible.length} matching entities`:"Connected entities"}</h2></div><span className="badge">Deterministic</span></div>{results.isFetching?<LoadingState label="Searching graph"/>:visible.length?<div className="entity-grid">{visible.map(item=><button type="button" key={item.id} className={`entity-card ${selected===item.id?"active":""}`} onClick={()=>setSelected(item.id)}><span className={`entity-icon entity-${item.type.toLowerCase()}`}>{entityIcon(item.type)}</span><span><strong>{item.name}</strong><small>{label(item.type)}{"documentCount" in item?` · ${item.documentCount} document${item.documentCount===1?"":"s"}`:` · ${item.documents.length} documents`}</small></span><ArrowRight/></button>)}</div>:<EmptyState icon={<Network/>} title="No graph entities yet" description="Build the workspace graph after uploading or processing at least one document."/>}
     {!search.trim()&&graph.data.edges.length>0&&<div className="relation-list"><h3>Recent relationships</h3>{graph.data.edges.slice(0,18).map(edge=><button type="button" key={edge.id} onClick={()=>setSelected(edge.sourceEntityId)}><strong>{names.get(edge.sourceEntityId)??"Entity"}</strong><span><ArrowRight/>{label(edge.type)}</span><strong>{names.get(edge.targetEntityId)??"Entity"}</strong></button>)}</div>}
    </Card>
    <Card className="entity-detail">{!selected?<EmptyState icon={<Sparkles/>} title="Select an entity" description="Choose a connected entity to inspect its documents, tasks, dates and evidence."/>:detail.isLoading?<LoadingState label="Loading entity relationships"/>:detail.isError||!detail.data?<ErrorState title="Entity unavailable" description="This entity is not available in your workspace."/>:<EntityDetail detail={detail.data} onSelect={setSelected}/>}</Card>
   </div>
   <Card className="graph-question"><div><span className="ai-icon"><Sparkles/></span><div><p className="eyebrow-label">GRAPH-GUIDED CROSS-DOCUMENT RETRIEVAL</p><h2>Ask across connected documents</h2><p>Matches entities, expands one relationship hop and ranks bounded source chunks. This is not vector RAG.</p></div></div><form onSubmit={submit}><textarea value={question} onChange={event=>setQuestion(event.target.value)} placeholder="What connects Gemini, Aakash and the Intellix project?" maxLength={500}/><button className="button button-primary" disabled={question.trim().length<2||ask.isPending}>{ask.isPending?<LoaderCircle className="spin"/>:<Sparkles/>}Ask workspace</button></form>{ask.isError&&<div className="form-error">{ask.error instanceof ApiError?ask.error.message:"The question could not be answered."}</div>}{ask.data&&<div className={`graph-answer ${ask.data.synthesisAvailable?"":"quota-limited"}`}><div><StatusBadge status={ask.data.synthesisAvailable?"READY":ask.data.status??"EVIDENCE_ONLY"}/><strong>{ask.data.synthesisAvailable?"Gemini synthesis":"Evidence-only answer"}</strong></div><p>{ask.data.answer}</p><div className="citation-list">{(ask.data.citations.length?ask.data.citations:ask.data.evidence).map((citation,index)=><div key={`${citation.documentId}-${citation.chunkIndex}-${index}`}><small>{citation.documentName} · Chunk {citation.chunkIndex}{citation.pageNumber?` · Page ${citation.pageNumber}`:""}</small><span>{citation.excerpt}</span></div>)}</div></div>}
   </Card>
  </>}
 </AppShell>;
}

function EntityDetail({detail,onSelect}:{detail:Detail;onSelect:(id:string)=>void}){return <div className="entity-detail-content"><div className="entity-detail-heading"><span className={`entity-icon entity-${detail.entity.type.toLowerCase()}`}>{entityIcon(detail.entity.type)}</span><div><p>{label(detail.entity.type)}</p><h2>{detail.entity.name}</h2></div></div><DetailSection title="Relationships">{[...detail.outgoingRelations.map(item=>({id:item.targetEntity.id,name:item.targetEntity.name,type:item.type,direction:"out"})),...detail.incomingRelations.map(item=>({id:item.sourceEntity.id,name:item.sourceEntity.name,type:item.type,direction:"in"}))].map(item=><button className="detail-link" type="button" onClick={()=>onSelect(item.id)} key={`${item.direction}-${item.id}-${item.type}`}><span>{item.direction==="in"?"←":"→"} {label(item.type)}</span><strong>{item.name}</strong></button>)}</DetailSection><DetailSection title="Connected documents">{detail.sourceDocuments.map(document=><div className="detail-row" key={document.id}><FileText/><span><strong>{document.name}</strong><small>{label(document.status)}</small></span></div>)}</DetailSection><DetailSection title="Connected tasks">{detail.connectedTasks.map(task=><div className="detail-row" key={task.id}><Users/><span><strong>{task.title}</strong><small>{label(task.status)} · {label(task.priority)}</small></span></div>)}</DetailSection><DetailSection title="Important dates">{detail.connectedDates.map(date=><div className="detail-row" key={date.id}><CalendarDays/><strong>{date.name}</strong></div>)}</DetailSection><DetailSection title="Source excerpts">{detail.sourceExcerpts.map((source,index)=><blockquote key={`${source.documentId}-${index}`}>{source.excerpt}</blockquote>)}</DetailSection></div>}
function DetailSection({title,children}:{title:string;children:React.ReactNode}){const items=Array.isArray(children)?children.filter(Boolean):children;return <section><h3>{title}</h3>{Array.isArray(items)&&!items.length?<p className="muted-copy">No connected items.</p>:items}</section>}
function Stat({icon,label:copy,value}:{icon:React.ReactNode;label:string;value:number}){return <article><span>{icon}</span><div><p>{copy}</p><strong>{value}</strong></div></article>}
function label(value:string){return value.replaceAll("_"," ").toLowerCase().replace(/\b\w/g,character=>character.toUpperCase())}
function entityIcon(type:EntityType){if(type==="DOCUMENT")return <FileText/>;if(type==="DATE")return <CalendarDays/>;if(type==="PERSON")return <Users/>;if(type==="TECHNOLOGY")return <Sparkles/>;return <Network/>}
