"use client";

import Link from "next/link";
import { useParams, useRouter } from "next/navigation";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { FormEvent, useMemo, useState } from "react";
import { ArrowLeft, Check, LoaderCircle, MessageSquare, Sparkles, Trash2 } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { DocumentFailureState } from "@/components/document-failure-state";
import { Card, ErrorState, LoadingState, PageHeader, StatusBadge } from "@/components/ui";
import { api, ApiError, type ActionItem, type DocumentRecord } from "@/lib/api";

type Tab="overview"|"summary"|"qa"|"actions"|"metadata";
export default function DocumentDetail(){
 const {documentId}=useParams<{documentId:string}>(),router=useRouter(),client=useQueryClient(),[tab,setTab]=useState<Tab>("overview"),[selected,setSelected]=useState<number[]>([]),[question,setQuestion]=useState(""),[answer,setAnswer]=useState<{answer:string;citations:{chunkIndex:number;pageNumber?:number;excerpt:string}[]}|null>(null),[notice,setNotice]=useState("");
 const query=useQuery({queryKey:["document",documentId],queryFn:()=>api<DocumentRecord>(`/documents/${documentId}`),refetchInterval:state=>["READY","FAILED"].includes(state.state.data?.status??"")?false:2500});const actions=query.data?.actionItems??[];const chosen=useMemo(()=>selected.map(i=>actions[i]).filter((item):item is ActionItem=>Boolean(item)),[selected,actions]);
 const tasks=useMutation({mutationFn:()=>api(`/documents/${documentId}/action-items/tasks`,{method:"POST",body:JSON.stringify({confirmed:true,items:chosen})}),onSuccess:async()=>{setNotice(`${chosen.length} task${chosen.length===1?"":"s"} created.`);setSelected([]);await Promise.all([client.invalidateQueries({queryKey:["tasks"]}),client.invalidateQueries({queryKey:["dashboard-summary"]})])},onError:cause=>setNotice(cause instanceof ApiError?cause.message:"Task creation failed.")});
 const ask=useMutation({mutationFn:()=>api<{answer:string;citations:{chunkIndex:number;pageNumber?:number;excerpt:string}[]}>(`/documents/${documentId}/questions`,{method:"POST",body:JSON.stringify({question})}),onSuccess:data=>{setAnswer(data);setQuestion("")}});
 const retry=useMutation({mutationFn:()=>api(`/documents/${documentId}/analyze`,{method:"POST"}),onSuccess:()=>client.invalidateQueries({queryKey:["document",documentId]})});
 const remove=useMutation({mutationFn:()=>api(`/documents/${documentId}`,{method:"DELETE"}),onSuccess:async()=>{await Promise.all([client.invalidateQueries({queryKey:["documents"]}),client.invalidateQueries({queryKey:["dashboard-summary"]})]);router.push("/documents")}});
 function submit(event:FormEvent){event.preventDefault();if(question.trim())ask.mutate()}
 return <AppShell title="Document intelligence">{query.isLoading?<LoadingState label="Loading document"/>:query.isError||!query.data?<ErrorState title="Document unavailable" description="This document could not be found in your workspace."/>:<><div className="detail-topline"><Link className="back-link" href="/documents"><ArrowLeft/>Documents</Link></div><PageHeader title={query.data.name} description="Review structured intelligence, grounded answers and confirmed actions." actions={<button type="button" className="button button-danger" onClick={()=>remove.mutate()} disabled={remove.isPending}><Trash2/>Delete</button>}/><div className="detail-meta"><StatusBadge status={query.data.status}/><span>{query.data.mimeType}</span><span>{(query.data.sizeBytes/1024).toFixed(1)} KB</span><span>Uploaded {new Date(query.data.createdAt).toLocaleDateString()}</span></div>
  {query.data.status==="FAILED"?<DocumentFailureState errorCode={query.data.errorCode} errorMessage={query.data.errorMessage} retrying={retry.isPending} retryError={retry.isError?(retry.error instanceof ApiError?retry.error.message:"Analysis could not be queued."):undefined} onRetry={()=>retry.mutate()}/>:query.data.status!=="READY"?<Card><div className="ui-state"><LoaderCircle className="spin"/><h2>Intellix is processing this document</h2><p>Current stage: {query.data.status.replaceAll("_"," ").toLowerCase()}</p></div></Card>:<>{query.data.errorCode==="EVIDENCE_ONLY"&&<Card><div className="ui-state"><Sparkles/><h2>Evidence-only mode</h2><p>External AI synthesis was unavailable. These results were extracted deterministically from the source text without invented content.</p></div></Card>}<div className="tab-list" role="tablist" aria-label="Document sections">{(["overview","summary","qa","actions","metadata"] as Tab[]).map(value=><button type="button" role="tab" aria-selected={tab===value} className={tab===value?"active":""} onClick={()=>setTab(value)} key={value}>{value==="qa"?"Q&A":value[0].toUpperCase()+value.slice(1)}</button>)}</div>
   {tab==="overview"&&<div className="analysis-grid"><div className="analysis-stack"><Card><h2>Summary</h2><p>{query.data.summary}</p></Card><Card><h2>Key points</h2><ul>{query.data.keyPoints?.map(point=><li key={point}>{point}</li>)}</ul></Card></div><div className="analysis-stack"><Card><h2>Keywords</h2><div className="keyword-list">{query.data.keywords?.map(word=><span key={word}>{word}</span>)}</div></Card><Card><h2>Important dates</h2>{query.data.importantDates?.length?query.data.importantDates.map(item=><div key={`${item.label}-${item.date}`}><strong>{item.label}</strong><p>{item.date}{item.context?` — ${item.context}`:""}</p></div>):<p>No important dates identified.</p>}</Card></div></div>}
   {tab==="summary"&&<Card className="analysis-stack"><h2>Document summary</h2><p>{query.data.summary}</p><h2>Key points</h2><ul>{query.data.keyPoints?.map(point=><li key={point}>{point}</li>)}</ul></Card>}
   {tab==="qa"&&<Card className="qa-panel"><h2><Sparkles/> Ask this document</h2><p>Answers are grounded in the source and include excerpts.</p>{answer&&<div className="answer-card"><p>{answer.answer}</p><div className="citation-list">{answer.citations.map(citation=><div key={`${citation.chunkIndex}-${citation.pageNumber}`}><small>Chunk {citation.chunkIndex}{citation.pageNumber?` · Page ${citation.pageNumber}`:""}</small><span>{citation.excerpt}</span></div>)}</div></div>}<form className="qa-form" onSubmit={submit}><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="What does this document say about…" aria-label="Question about document"/><button className="button button-primary" disabled={!question.trim()||ask.isPending}>{ask.isPending?<LoaderCircle className="spin"/>:<MessageSquare/>}Ask</button></form>{ask.isError&&<div className="form-error" role="alert">{ask.error instanceof ApiError?ask.error.message:"The question could not be answered."}</div>}</Card>}
   {tab==="actions"&&<Card className="analysis-stack"><h2>Action items</h2><p>Select the actions you approve. Tasks are never created without confirmation.</p><div className="action-list">{actions.map((item,index)=><label key={`${item.title}-${index}`}><input type="checkbox" checked={selected.includes(index)} onChange={()=>setSelected(items=>items.includes(index)?items.filter(i=>i!==index):[...items,index])}/><span><strong>{item.title}</strong><small>{item.priority}{item.dueDate?` · ${new Date(item.dueDate).toLocaleDateString()}`:""}</small>{item.description&&<small>{item.description}</small>}</span></label>)}</div><button type="button" className="button button-primary" disabled={!chosen.length||tasks.isPending} onClick={()=>tasks.mutate()}><Check/>Confirm and create {chosen.length||""} tasks</button>{notice&&<p role="status">{notice}</p>}</Card>}
   {tab==="metadata"&&<Card className="analysis-stack"><h2>Metadata</h2><p><strong>File type:</strong> {query.data.mimeType}</p><p><strong>Size:</strong> {(query.data.sizeBytes/1024).toFixed(1)} KB</p><p><strong>Created:</strong> {new Date(query.data.createdAt).toLocaleString()}</p><p><strong>Updated:</strong> {new Date(query.data.updatedAt).toLocaleString()}</p></Card>}
  </>}</>}
 </AppShell>;
}
