"use client";
import { useParams } from "next/navigation";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { FormEvent, useMemo, useState } from "react";
import { Check, LoaderCircle, MessageSquare, Sparkles } from "lucide-react";
import { WorkspaceHeader } from "@/components/workspace-header";
import { api, ApiError, type ActionItem, type DocumentRecord } from "@/lib/api";

export default function DocumentDetail(){const {documentId}=useParams<{documentId:string}>(),client=useQueryClient(),[selected,setSelected]=useState<number[]>([]),[question,setQuestion]=useState(""),[answer,setAnswer]=useState<{answer:string;citations:{chunkIndex:number;pageNumber?:number;excerpt:string}[]}|null>(null),[notice,setNotice]=useState("");
 const query=useQuery({queryKey:["document",documentId],queryFn:()=>api<DocumentRecord>(`/documents/${documentId}`),refetchInterval:(state)=>state.state.data?.status==="READY"||state.state.data?.status==="FAILED"?false:2500});const actions=query.data?.actionItems??[];
 const chosen=useMemo(()=>selected.map(i=>actions[i]).filter((item):item is ActionItem=>Boolean(item)),[selected,actions]);
 const tasks=useMutation({mutationFn:()=>api(`/documents/${documentId}/action-items/tasks`,{method:"POST",body:JSON.stringify({confirmed:true,items:chosen})}),onSuccess:async()=>{setNotice(`${chosen.length} task${chosen.length===1?"":"s"} created.`);setSelected([]);await client.invalidateQueries({queryKey:["tasks"]})},onError:(cause)=>setNotice(cause instanceof ApiError?cause.message:"Task creation failed.")});
 const ask=useMutation({mutationFn:()=>api<{answer:string;citations:{chunkIndex:number;pageNumber?:number;excerpt:string}[]}>(`/documents/${documentId}/questions`,{method:"POST",body:JSON.stringify({question})}),onSuccess:(data)=>{setAnswer(data);setQuestion("")}});
 function submit(event:FormEvent){event.preventDefault();if(question.trim())ask.mutate()}
 return <><WorkspaceHeader/><main className="product-page detail-page">{query.isLoading?<div className="empty-state"><LoaderCircle className="spin"/></div>:query.isError||!query.data?<div className="empty-state"><p>Document not found or unavailable.</p></div>:<><header className="detail-header"><div><span className={`status ${query.data.status.toLowerCase()}`}>{query.data.status.replaceAll("_"," ")}</span><h1>{query.data.name}</h1><p>{(query.data.sizeBytes/1024).toFixed(1)} KB · {query.data.mimeType}</p></div></header>
 {query.data.status==="FAILED"?<div className="error-card"><h2>Processing failed</h2><p>{query.data.errorMessage??"The document could not be processed."}</p></div>:query.data.status!=="READY"?<div className="processing-card"><LoaderCircle className="spin"/><div><h2>Intellix is processing this document</h2><p>Current stage: {query.data.status.replaceAll("_"," ").toLowerCase()}</p></div></div>:<div className="analysis-grid"><section className="analysis-main"><article><span className="kicker">SUMMARY</span><h2>What this document says</h2><p>{query.data.summary}</p></article><article><h2>Key points</h2><ul>{query.data.keyPoints?.map(point=><li key={point}>{point}</li>)}</ul></article><article><h2>Important dates</h2>{query.data.importantDates?.length?<div className="date-list">{query.data.importantDates.map(item=><div key={`${item.label}-${item.date}`}><strong>{item.label}</strong><time>{item.date}</time>{item.context&&<p>{item.context}</p>}</div>)}</div>:<p>No important dates were identified.</p>}</article></section><aside><article><h2>Keywords</h2><div className="keyword-list">{query.data.keywords?.map(word=><span key={word}>{word}</span>)}</div></article><article><h2>Action items</h2><p>Select the items you want. Tasks are never created without confirmation.</p><div className="action-list">{actions.map((item,index)=><label key={`${item.title}-${index}`}><input type="checkbox" checked={selected.includes(index)} onChange={()=>setSelected(items=>items.includes(index)?items.filter(i=>i!==index):[...items,index])}/><span><strong>{item.title}</strong><small>{item.priority}{item.dueDate?` · ${new Date(item.dueDate).toLocaleDateString()}`:""}</small></span></label>)}</div><button className="button button-primary" disabled={!chosen.length||tasks.isPending} onClick={()=>tasks.mutate()}><Check size={15}/>Confirm and create {chosen.length||""} tasks</button>{notice&&<p className="inline-notice">{notice}</p>}</article></aside><section className="qa-panel"><div><Sparkles size={19}/><span><h2>Ask this document</h2><p>Answers use the most relevant document chunks and include citations.</p></span></div>{answer&&<div className="answer"><p>{answer.answer}</p><small>{answer.citations.map(c=>`Chunk ${c.chunkIndex}${c.pageNumber?`, page ${c.pageNumber}`:""}`).join(" · ")}</small></div>}<form onSubmit={submit}><input value={question} onChange={e=>setQuestion(e.target.value)} placeholder="What does the document say about…" aria-label="Question about document"/><button disabled={!question.trim()||ask.isPending}>{ask.isPending?<LoaderCircle className="spin" size={16}/>:<MessageSquare size={16}/>}Ask</button></form>{ask.isError&&<p className="form-error">{ask.error instanceof ApiError?ask.error.message:"Could not answer the question."}</p>}</section></div>}</>}</main></>}
