"use client";

import Link from "next/link";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { ChangeEvent, DragEvent, useMemo, useRef, useState } from "react";
import { FileText, LoaderCircle, Search, Upload } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { Card, EmptyState, ErrorState, LoadingState, PageHeader, StatusBadge } from "@/components/ui";
import { api, ApiError, type DocumentRecord } from "@/lib/api";

const terminal = new Set(["READY","FAILED"]);
export default function DocumentsPage(){
 const client=useQueryClient(),input=useRef<HTMLInputElement>(null),[error,setError]=useState(""),[search,setSearch]=useState(""),[status,setStatus]=useState("ALL"),[type,setType]=useState("ALL"),[sort,setSort]=useState("NEWEST"),[dragging,setDragging]=useState(false);
 const query=useQuery({queryKey:["documents"],queryFn:()=>api<DocumentRecord[]>("/documents"),refetchInterval:(state)=>state.state.data?.some(doc=>!terminal.has(doc.status))?2500:false});
 const upload=useMutation({mutationFn:async(file:File)=>{const body=new FormData();body.append("file",file);return api<DocumentRecord>("/documents",{method:"POST",body})},onSuccess:async()=>{setError("");await Promise.all([client.invalidateQueries({queryKey:["documents"]}),client.invalidateQueries({queryKey:["dashboard-summary"]})])},onError:(cause)=>setError(cause instanceof ApiError?cause.message:"Upload failed. Verify the API is running and try again.")});
 const documents=useMemo(()=>[...(query.data??[])].filter(doc=>doc.name.toLowerCase().includes(search.toLowerCase())&&(status==="ALL"||doc.status===status)&&(type==="ALL"||fileGroup(doc.mimeType)===type)).sort((a,b)=>sort==="NAME"?a.name.localeCompare(b.name):sort==="OLDEST"?+new Date(a.createdAt)-+new Date(b.createdAt):+new Date(b.createdAt)-+new Date(a.createdAt)),[query.data,search,status,type,sort]);
 function submit(file?:File){if(file)upload.mutate(file)} function choose(event:ChangeEvent<HTMLInputElement>){submit(event.target.files?.[0]);event.target.value=""} function drop(event:DragEvent){event.preventDefault();setDragging(false);submit(event.dataTransfer.files[0])}
 return <AppShell title="Documents"><PageHeader eyebrow="DOCUMENT INTELLIGENCE" title="Documents" description="Upload, process and explore every workspace source from one secure place." actions={<button type="button" className="button button-primary" onClick={()=>input.current?.click()} disabled={upload.isPending}>{upload.isPending?<LoaderCircle className="spin"/>:<Upload/>}Upload document</button>}/><input ref={input} hidden type="file" accept=".pdf,.txt,.png,.jpg,.jpeg" onChange={choose}/>
  <section className={`upload-zone ${dragging?"is-dragging":""}`} onDragOver={event=>{event.preventDefault();setDragging(true)}} onDragLeave={()=>setDragging(false)} onDrop={drop}><span><Upload/></span><h2>Drop a document here</h2><p>PDF, TXT, PNG or JPG up to 10 MB</p><button type="button" className="button button-secondary" onClick={()=>input.current?.click()}>Choose file</button></section>
  {error&&<div className="form-error" role="alert">{error}</div>}
  <div className="toolbar"><label><Search/><span className="sr-only">Search documents</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search documents"/></label><select aria-label="Filter by status" value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All statuses</option>{["UPLOADED","EXTRACTING","OCR_PROCESSING","ANALYZING","READY","FAILED"].map(value=><option key={value}>{value}</option>)}</select><select aria-label="Filter by file type" value={type} onChange={e=>setType(e.target.value)}><option value="ALL">All file types</option><option value="PDF">PDF</option><option value="TEXT">Text</option><option value="IMAGE">Image</option></select><select aria-label="Sort documents" value={sort} onChange={e=>setSort(e.target.value)}><option value="NEWEST">Newest first</option><option value="OLDEST">Oldest first</option><option value="NAME">Name</option></select></div>
  {query.isLoading?<LoadingState label="Loading documents"/>:query.isError?<ErrorState description="Documents could not be loaded. Sign in again or verify the API connection."/>:!query.data?.length?<EmptyState icon={<FileText/>} title="No documents yet" description="Upload your first file to generate a summary, actions, dates and grounded answers."/>:!documents.length?<EmptyState icon={<Search/>} title="No matching documents" description="Try a different search term or filter."/>:<Card className="document-table"><div className="data-list"><div className="data-row header"><span>File</span><span>Type</span><span>Size</span><span>Status</span><span>Uploaded</span></div>{documents.map(doc=><Link href={`/documents/${doc.id}`} className="data-row" key={doc.id}><span className="file-meta"><b title={doc.name}>{doc.name}</b><small>Open intelligence</small></span><span>{fileGroup(doc.mimeType)}</span><span>{formatBytes(doc.sizeBytes)}</span><StatusBadge status={doc.status}/><time>{new Date(doc.createdAt).toLocaleDateString()}</time></Link>)}</div></Card>}
 </AppShell>;
}
function fileGroup(mime:string){if(mime.includes("pdf"))return "PDF";if(mime.startsWith("image/"))return "IMAGE";return "TEXT"} function formatBytes(bytes:number){return bytes<1024?`${bytes} B`:`${(bytes/1024).toFixed(1)} KB`}
